version: 2.1

jobs:
  test:
    parallelism: 2
    docker: 
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            TEST_FILES=$(circleci tests glob "**/*.sh" | circleci tests split --split-by=name)
            echo $TEST_FILES
            bash $TEST_FILES
workflows:
  version: 2
  test:
    jobs:
      - test