version: 2.1

orbs:
  win: circleci/windows@2.4.1

jobs:
  build-docker:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - run: echo "docker image"
  build-machine:
    machine:
      image: ubuntu-2004:202111-01
    steps:
      - run: echo "machine image"
  build-macos:
    macos:
      xcode: 13.2.0
    steps:
      - run: echo "macos image"
  build-windows:
    executor: win/default
    steps:
      - run: Write-Host 'windows image'


workflows:
  version: 2
  docker:
    jobs:
      - build-docker
  machine: 
    jobs:
      - build-machine
  macos:
    jobs:
      - build-macos
  windows:
    jobs:
      - build-windows